backend:
  name: git-gateway
  branch: main # Si tu rama principal se llama 'master', cambia esto a master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Stock", name: "stock", widget: "number"}
      - {label: "Descripción", name: "body", widget: "markdown"}
      - {label: "Categoría", name: "category", widget: "select", options: ["New Arrival", "Jacket", "Clothes", "Sale"]}
      - label: "Carrusel de Fotos"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Imagen", name: "image", widget: "image"}

  - name: "configuracion"
    label: "Ajustes de Web"
    files:
      - label: "Banners y Textos"
        name: "home"
        file: "content/home.yml"
        fields:
          - {label: "Título Hero", name: "hero_title", widget: "string"}
          - {label: "Imagen Principal", name: "hero_image", widget: "image"}

