backend:
  name: git-gateway
  branch: main 

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Precio", name: "price", widget: "number"}
      - {label: "Stock", name: "stock", widget: "number"}
      - label: "Fotos (Carrusel)"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Imagen", name: "image", widget: "image"}
